server {
    listen 80;
    server_name localhost;

    # Routage des ressources statiques (Single Page Application)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Mécanisme de fallback pour le routage côté client (React Router)
        try_files $uri $uri/ /index.html;
    }

    # Proxy inverse pour les transactions API
    location /api/ {
        # Transmission de la requête au conteneur API via le réseau Docker
        proxy_pass http://api:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}